# Generated by Django 4.2.14 on 2025-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actualite",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="actualite",
            name="lien",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
