# Generated by Django 4.2.14 on 2025-02-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0002_actualite_image_url_actualite_lien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualite",
            name="titre",
            field=models.CharField(max_length=500),
        ),
    ]
