# Generated by Django 4.2.14 on 2025-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accueil", "0003_alter_actualite_titre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualite",
            name="contenu",
            field=models.TextField(blank=True, null=True),
        ),
    ]
