# Generated by Django 4.2.14 on 2025-02-05 17:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("projets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
