# Generated by Django 4.2.14 on 2025-02-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("projets", "0002_alter_projet_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projet",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projets", to="tags.tag"
            ),
        ),
    ]
